server:
  port: 8093

spring:
  application:
    name: HYSTRIX-DASHBOARD
  config:
    import: optional:configserver:http://localhost:8094

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

# comment these if want to load the properties form  github using cloud-config-server ms
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost